Resolve getActivePresentation Authorization issue
This resolves an issue I was seeing when walking through the quickstart guide here: https://developers.google.com/gsuite/add-ons/editors/slides/quickstart/progress-bar  

Essentially I am seeing the following in StackDriver Logs for a "Simple Trigger" when I refresh my Google Presentation browser window as directed to do in the guide:

```
Exception: Authorization is required to perform that action.
    at [unknown function](progress:6:30)
```

This change is to avoid running `getActivePresentation` in the global scope. Note that there are some references to fixing this by running any function in the Apps Script editor see https://developers.google.com/apps-script/guides/support/troubleshooting#execution_transcript, which appears to have resolve others experiencing this issue, but there are also some suggesting that this no longer works, see https://webapps.stackexchange.com/a/136707 and the comment from kurokirasama.

I'm unsure as to what has changed to require this, but this at least resolves my immediate issue.